import express from 'express'
import helmet from 'helmet'
import cors from 'cors'
import rateLimit from 'express-rate-limit'
import cookieParser from 'cookie-parser'
import bcrypt from 'bcryptjs'
import crypto from 'crypto'
import multer from 'multer'
import { v2 as cloudinary } from 'cloudinary'
import { Types } from 'mongoose'
import { env } from './config.js'
import { AdminSession, Article, Comment, Like } from './models.js'
import { articleSchema, commentSchema, loginSchema, visitorSchema } from './validators.js'
import { asyncRoute, cleanContent, cookieOptions, hash, readingTime, requireAdmin } from './utils.js'

const app=express();
const localOrigin=/^https?:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/
const corsOrigin=(origin:string|undefined,callback:(error:Error|null,allow?:boolean)=>void)=>{const normalized=origin?.replace(/\/$/,'');if(!origin||env.clientUrls.includes(normalized||'')||(!env.production&&localOrigin.test(origin)))return callback(null,true);callback(new Error(`CORS origin is not allowed: ${origin}`))}
app.set('trust proxy',1);app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));app.use(cors({origin:corsOrigin,credentials:true,methods:['GET','HEAD','PUT','PATCH','POST','DELETE','OPTIONS'],allowedHeaders:['Content-Type'],maxAge:86400}));app.use(express.json({limit:'700kb'}));app.use(cookieParser(env.cookieSecret));
const limiter=(windowMs:number,max:number)=>rateLimit({windowMs,max,standardHeaders:true,legacyHeaders:false,message:{message:'Too many requests. Please try again shortly.'}})
const routeValue=(value:string|string[])=>Array.isArray(value)?value[0]:value
const id=(value:string|string[])=>Types.ObjectId.isValid(routeValue(value))
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:6*1024*1024},fileFilter:(_req,file,cb)=>cb(null,['image/jpeg','image/png','image/webp','image/avif'].includes(file.mimetype))})
if(env.cloudinary.cloudName)cloudinary.config({cloud_name:env.cloudinary.cloudName,api_key:env.cloudinary.apiKey,api_secret:env.cloudinary.apiSecret,secure:true})
const publicQuery=(query:Record<string,unknown>)=>({status:'published',...(query.category?{category:new RegExp(`^${String(query.category).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`,'i')}:{})})

app.get('/health',(_req,res)=>res.json({ok:true}))
app.get('/sitemap.xml',asyncRoute(async(_req,res)=>{const stories=await Article.find({status:'published'}).select('slug updatedAt').lean();const urls=[`${env.siteUrl}/`,`${env.siteUrl}/archive`,`${env.siteUrl}/about`,...stories.map(s=>`${env.siteUrl}/blog/${s.slug}`)];res.type('application/xml').send(`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map((url,i)=>`<url><loc>${url}</loc>${i>2?`<lastmod>${stories[i-3].updatedAt.toISOString()}</lastmod>`:''}</url>`).join('')}</urlset>`)}))
app.get('/api/articles/search',asyncRoute(async(req,res)=>{const q=String(req.query.q||'').trim();if(!q)return res.json({data:[],page:1,total:0,pages:0});const regex=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const data=await Article.find({status:'published',$or:[{title:regex},{excerpt:regex},{content:regex},{category:regex},{tags:regex}]}).sort({publishedAt:-1}).limit(50).lean();res.json({data,page:1,total:data.length,pages:1})}))
app.get('/api/articles',asyncRoute(async(req,res)=>{const page=Math.max(1,Number(req.query.page)||1),limit=Math.min(100,Math.max(1,Number(req.query.limit)||10));const filter:any=publicQuery(req.query);if(req.query.featured==='true')filter.featured=true;const [data,total]=await Promise.all([Article.find(filter).sort({featured:-1,publishedAt:-1}).skip((page-1)*limit).limit(limit).lean(),Article.countDocuments(filter)]);res.json({data,page,total,pages:Math.ceil(total/limit)})}))
app.get('/api/categories',asyncRoute(async(_req,res)=>{const data=await Article.aggregate([{$match:{status:'published'}},{$group:{_id:'$category',count:{$sum:1}}},{$sort:{_id:1}}]);res.json(data.map(x=>({name:x._id,count:x.count}))) }))
app.get('/api/articles/:id/related',asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});const source=await Article.findById(articleId);if(!source)return res.status(404).json({message:'Article not found.'});const data=await Article.find({_id:{$ne:source._id},status:'published',$or:[{category:source.category},{tags:{$in:source.tags}}]}).sort({publishedAt:-1}).limit(3).lean();res.json(data)}))
app.get('/api/articles/:id/comments',asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.json([]);res.json(await Comment.find({articleId,status:'visible'}).sort({createdAt:-1}).lean())}))
app.post('/api/articles/:id/comments',limiter(15*60_000,8),asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});const input=commentSchema.safeParse(req.body);if(!input.success)return res.status(400).json({message:'Please provide a name and a short, thoughtful comment.'});const article=await Article.findOne({_id:articleId,status:'published'});if(!article)return res.status(404).json({message:'Article not found.'});const ip=String(req.ip||'unknown');const ipHash=hash(`${ip}:${env.cookieSecret}`);const existing=await Comment.countDocuments({articleId:article._id,ipHash,createdAt:{$gt:new Date(Date.now()-60*60_000)}});if(existing>=3)return res.status(429).json({message:'Please wait a little before posting another comment.'});const comment=await Comment.create({...input.data,articleId:article._id,ipHash,status:'visible'});await Article.updateOne({_id:article._id},{$inc:{commentsCount:1}});res.status(201).json(comment)}))
app.post('/api/articles/:id/like',limiter(60*60_000,30),asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});const input=visitorSchema.safeParse(req.body);if(!input.success)return res.status(400).json({message:'Invalid visitor.'});const article=await Article.findOne({_id:articleId,status:'published'});if(!article)return res.status(404).json({message:'Article not found.'});try{await Like.create({articleId:article._id,visitorId:input.data.visitorId});const updated=await Article.findByIdAndUpdate(article._id,{$inc:{likesCount:1}},{new:true});res.status(201).json({likesCount:updated?.likesCount||0})}catch(error:any){if(error?.code===11000)return res.status(409).json({message:'You have already liked this story.'});throw error}}))
app.delete('/api/articles/:id/like',asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});const input=visitorSchema.safeParse(req.body);if(!input.success)return res.status(400).json({message:'Invalid visitor.'});const deleted=await Like.findOneAndDelete({articleId,visitorId:input.data.visitorId});if(deleted){const updated=await Article.findByIdAndUpdate(articleId,{$inc:{likesCount:-1}},{new:true});return res.json({likesCount:Math.max(0,updated?.likesCount||0)})}const article=await Article.findById(articleId);res.json({likesCount:article?.likesCount||0})}))
app.get('/api/articles/:slug',asyncRoute(async(req,res)=>{const article:any=await Article.findOne({slug:routeValue(req.params.slug),status:'published'}).lean();if(!article)return res.status(404).json({message:'Article not found.'});void Article.updateOne({_id:article._id},{$inc:{viewsCount:1}});res.json(article)}))

app.post('/api/admin/login',limiter(15*60_000,8),asyncRoute(async(req,res)=>{const input=loginSchema.safeParse(req.body);if(!input.success||!env.adminEmail||!env.adminPassword)return res.status(401).json({message:'Invalid email or password.'});const emailMatch=input.data.email.toLowerCase()===env.adminEmail.toLowerCase();const passwordMatch=await bcrypt.compare(input.data.password,env.adminPassword);if(!emailMatch||!passwordMatch)return res.status(401).json({message:'Invalid email or password.'});const raw=crypto.randomBytes(32).toString('base64url');await AdminSession.create({tokenHash:hash(raw),expiresAt:new Date(Date.now()+14*24*60*60_000)});res.cookie('margin_session',raw,cookieOptions).json({email:env.adminEmail})}))
app.post('/api/admin/logout',asyncRoute(async(req,res)=>{const token=req.signedCookies?.margin_session;if(token)await AdminSession.deleteOne({tokenHash:hash(token)});res.clearCookie('margin_session',{...cookieOptions,maxAge:undefined}).status(204).end()}))
app.get('/api/admin/me',requireAdmin,(_req,res)=>res.json({email:env.adminEmail}))
app.post('/api/admin/uploads',requireAdmin,upload.single('image'),asyncRoute(async(req,res)=>{if(!req.file)return res.status(400).json({message:'Choose a JPEG, PNG, WebP, or AVIF image under 6 MB.'});if(!env.cloudinary.cloudName)return res.status(503).json({message:'Image uploads require Cloudinary credentials on the server.'});const result=await new Promise<any>((resolve,reject)=>{const stream=cloudinary.uploader.upload_stream({folder:'the-margin/covers',resource_type:'image'},(error,value)=>error?reject(error):resolve(value));stream.end(req.file!.buffer)});res.status(201).json({url:result.secure_url,alt:'',width:result.width,height:result.height})}))
app.get('/api/admin/articles',requireAdmin,asyncRoute(async(_req,res)=>res.json(await Article.find().sort({updatedAt:-1}).lean())))
app.post('/api/admin/articles',requireAdmin,asyncRoute(async(req,res)=>{const input=articleSchema.safeParse(req.body);if(!input.success)return res.status(400).json({message:'Check the required article fields.',issues:input.error.flatten()});const data={...input.data,content:cleanContent(input.data.content),readingTime:readingTime(input.data.content),publishedAt:input.data.status==='published'?new Date():undefined};try{res.status(201).json(await Article.create(data))}catch(error:any){if(error?.code===11000)return res.status(409).json({message:'That slug is already in use.'});throw error}}))
app.put('/api/admin/articles/:id',requireAdmin,asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});const input=articleSchema.safeParse(req.body);if(!input.success)return res.status(400).json({message:'Check the required article fields.',issues:input.error.flatten()});const prior=await Article.findById(articleId);if(!prior)return res.status(404).json({message:'Article not found.'});const data:any={...input.data,content:cleanContent(input.data.content),readingTime:readingTime(input.data.content)};if(input.data.status==='published'&&!prior.publishedAt)data.publishedAt=new Date();if(input.data.status==='draft')data.publishedAt=undefined;try{res.json(await Article.findByIdAndUpdate(articleId,data,{new:true,runValidators:true}))}catch(error:any){if(error?.code===11000)return res.status(409).json({message:'That slug is already in use.'});throw error}}))
app.delete('/api/admin/articles/:id',requireAdmin,asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id);if(!id(articleId))return res.status(404).json({message:'Article not found.'});await Promise.all([Article.findByIdAndDelete(articleId),Like.deleteMany({articleId}),Comment.deleteMany({articleId})]);res.status(204).end()}))
app.patch('/api/admin/articles/:id/:action',requireAdmin,asyncRoute(async(req,res)=>{const articleId=routeValue(req.params.id),action=routeValue(req.params.action);if(!id(articleId)||!['publish','unpublish'].includes(action))return res.status(400).json({message:'Invalid action.'});const publish=action==='publish';const article=await Article.findByIdAndUpdate(articleId,{status:publish?'published':'draft',publishedAt:publish?new Date():undefined},{new:true});if(!article)return res.status(404).json({message:'Article not found.'});res.json(article)}))
app.get('/api/admin/comments',requireAdmin,asyncRoute(async(_req,res)=>res.json(await Comment.find().sort({createdAt:-1}).lean())))
app.patch('/api/admin/comments/:id',requireAdmin,asyncRoute(async(req,res)=>{const status=['visible','pending','hidden'].includes(req.body.status)?req.body.status:null;if(!status)return res.status(400).json({message:'Invalid comment status.'});const comment=await Comment.findByIdAndUpdate(req.params.id,{status},{new:true});if(!comment)return res.status(404).json({message:'Comment not found.'});res.json(comment)}))
app.delete('/api/admin/comments/:id',requireAdmin,asyncRoute(async(req,res)=>{const comment=await Comment.findByIdAndDelete(req.params.id);if(!comment)return res.status(404).json({message:'Comment not found.'});await Article.updateOne({_id:comment.articleId},{$inc:{commentsCount:-1}});res.status(204).end()}))
app.use((_req,res)=>res.status(404).json({message:'Route not found.'}));app.use((error:any,_req:any,res:any,_next:any)=>{console.error(error);res.status(500).json({message:'The server encountered an unexpected error.'})});
export default app
