import { connectDatabase } from './config.js'
import { Article, Comment, Like } from './models.js'

const img=(id:string,alt:string)=>({url:`https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=85`,alt})
const stories=[
 {title:'The Art of Leaving Room',slug:'the-art-of-leaving-room',excerpt:'A case for the unfilled page, the spare shelf, and the small spaces that let a life breathe.',category:'Life',tags:['attention','home','slowness'],featured:true,coverImage:img('photo-1494438639946-1ebd1d20bf85','Light-filled living room'),content:`<p>There is a particular kind of wealth in an empty corner. It is not the wealth of having less for its own sake, but the gentler abundance of being able to see what is already there.</p><p>We have become remarkably good at filling the frame. A calendar asks to be optimized; a shelf asks to be styled; a thought asks to become a take before it has found its proper shape.</p><blockquote>Space is not what remains when nothing happened. It is part of what makes anything meaningful.</blockquote><h2>The useful pause</h2><p>Leaving room begins as a practical choice. A blank afternoon. A margin around a paragraph. One uncluttered surface in a home. Then, almost without announcing itself, it becomes a way of meeting the world.</p><p>When every inch is spoken for, we have nowhere to put a new idea. When every minute has a job, surprise starts to feel like an interruption rather than an invitation.</p><hr><p>Perhaps the task is not to empty our lives, but to make a few more places where life can arrive.</p>`},
 {title:'Tools Should Disappear Into the Work',slug:'tools-should-disappear-into-the-work',excerpt:'The best tools do not demand our attention. They make a little more room for it.',category:'Technology',tags:['tools','technology','craft'],coverImage:img('photo-1516321318423-f06f85e504b3','Person working at a laptop'),content:`<p>A good tool has a strange humility. It meets you at the edge of an intention, helps you across, and then gets out of the way.</p><h2>Friction with a purpose</h2><p>Not every friction is a flaw. The click of a camera shutter, the resistance of a pencil, and the quiet ceremony of opening a notebook can all make us more deliberate.</p><p>But software often confuses activity with attention. It offers panels, nudges, and metrics until the work itself becomes a small region in the middle of a busy room.</p><blockquote>The point of a tool is not to make us feel productive. It is to help us make something worth keeping.</blockquote><p>The test is simple: after using it, are you more present to the work, or more aware of the tool?</p>`},
 {title:'A Walk Without a Destination',slug:'a-walk-without-a-destination',excerpt:'What changes when the route is not the point, and the afternoon belongs to no one in particular.',category:'Creativity',tags:['walking','creativity','city'],coverImage:img('photo-1470214304380-aadaedcfff1b','Person walking down a sunlit city street'),content:`<p>The neighborhood looks different when you are not trying to get anywhere. A familiar street begins to offer its smaller arrangements: a baker shaking flour from an apron, a bicycle wrapped in ivy, the slow choreography at a crossing.</p><h2>Permission to wander</h2><p>Walking without a destination is a tiny refusal of the idea that every experience must be useful. It returns the day to a scale the body understands.</p><p>Ideas do not always arrive at the desk. Sometimes they need the ordinary rhythm of feet on pavement before they can become audible.</p>`},
 {title:'What a Well-Made Object Knows',slug:'what-a-well-made-object-knows',excerpt:'A chair, a cup, a pair of scissors: small lessons in care, proportion, and the dignity of use.',category:'Design',tags:['objects','design','craft'],coverImage:img('photo-1505693416388-ac5ce068fe85','Warmly lit chair in a minimal home'),content:`<p>You can often tell when someone has thought about the hand. It is there in the place a thumb naturally rests, in the weight of a handle, in the way a drawer closes without asking for applause.</p><p>Well-made objects are not loud. They simply continue to be useful long after the novelty has left the room.</p><h2>Use is a kind of affection</h2><p>We mistake newness for value because newness is easy to notice. But a useful object gains a different beauty through repetition: the polished spot, the softened edge, the private history of being reached for.</p>`},
 {title:'The Readable Life',slug:'the-readable-life',excerpt:'Why a few carefully chosen boundaries can make the days more legible—and more our own.',category:'Ideas',tags:['habits','attention','ideas'],coverImage:img('photo-1499750310107-5fef28a66643','Notebook and pen on a quiet desk'),content:`<p>A readable life has a few recurring shapes. Not rigid rituals, but small landmarks that keep the days from blurring into one another.</p><p>Tea before the screen. A phone left in another room at dinner. A book that travels in the bag. These are modest choices, yet they make an argument about what deserves to remain available.</p><blockquote>Attention is not a resource to spend. It is a place to live.</blockquote><p>We cannot control the tempo of the world. We can choose, now and then, the rhythm of a single hour.</p>`},
 {title:'On Keeping a Commonplace Book',slug:'on-keeping-a-commonplace-book',excerpt:'A notebook for collecting the sentences, questions, and fragments that refuse to leave you alone.',category:'Culture',tags:['books','writing','culture'],coverImage:img('photo-1455390582262-044cdead277a','Handwriting in a notebook'),content:`<p>The commonplace book is a record of encounters. It does not have to be organized beautifully, though it may become beautiful because it has been used.</p><p>Copying a sentence by hand gives it a second life. It moves from someone else’s page into the landscape of your own attention.</p><h2>A conversation over time</h2><p>The fragments accumulate. A line of poetry sits beside a question from a meeting, beside the name of a tree. Years later, you discover they were speaking to one another all along.</p>`}
]
async function seed(){await connectDatabase();const existing=await Article.countDocuments();if(existing){console.log(`Database already contains ${existing} articles; nothing was changed.`);process.exit(0)}await Article.insertMany(stories.map((story,i)=>({...story,author:{name:'Elin Hayes'},status:'published',readingTime:Math.max(1,Math.ceil(story.content.replace(/<[^>]+>/g,' ').split(/\s+/).length/220)),likesCount:Math.max(7,31-i*3),commentsCount:0,viewsCount:0,publishedAt:new Date(Date.UTC(2026,8,21-i*2))})));console.log(`Seeded ${stories.length} editorial stories.`);process.exit(0)}seed().catch(error=>{console.error(error);process.exit(1)})
